app/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

LAZY_URLS = [
    path('lazy-bg-video/', views.lazy_background_video, name='lazy_bg_video'),
]

AUTH_URLS = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.RegistrationView.as_view(), name='signup'),
]

PROFILE_URLS = [
    path('users/<int:pk>/', views.UserProfileView.as_view(), name='user_profile'),
    path('users/<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('users/', views.redirect_to_me, name='user_profile'),
    path('users/me', views.UserProfileView.as_view(), name='user_profile_self'),
]

HOME_URLS = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('upload_pfp/', views.change_pfp, name='upload_pfp'),
]

CHAT_URLS = [
    path('groups/', views.ChatGroupListView.as_view(), name='chat_group_list'),
    path('groups/<int:pk>/', views.ChatGroupView.as_view(), name='chat_group'),
    path('groups/<str:group_name>/', views.ChatGroupView.as_view(), name='chat_group'),
]

urlpatterns = [
    *LAZY_URLS,
    *AUTH_URLS,
    *HOME_URLS,
    *PROFILE_URLS,
    *CHAT_URLS,
]

app/live_chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('tools/', include('tools.urls')),
    path('cases/', include('cases.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/tools/urls.py
from django.urls import path

from . import views

app_name = 'tools'

PIXELATE_SVG_URLS = [
    path('svg-pixelation/', views.SVGPixelationView.as_view(), name='svg_pixelation'),
]

urlpatterns = [
    *PIXELATE_SVG_URLS,
]

app/chat/models.py
from io import BytesIO

from PIL import Image
from django.contrib.auth.models import AbstractUser
from django.core.files.base import ContentFile
from django.db import models

from typing import Union

BaseModel = models.Model

class User(AbstractUser):
    pass

class PFP(BaseModel):
    image = models.ImageField(upload_to='profile_pics/', default='default/user_default.png')
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='pfp')

    def save(self, *args, **kwargs):
        if self.image and 'user_default.png' not in self.image.name:
            img = Image.open(self.image)

            img_format = img.format
            img = img.resize((512, 512))

            buf = BytesIO()
            img.save(buf, format=img_format, quality=90)

            file_name = '{}_profile.jpg'.format(self.user.username)

            self.image.save(file_name, ContentFile(buf.getvalue()), save=False)

        super(PFP, self).save(*args, **kwargs)

class ChatGroup(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # current_online = models.IntegerField()

    def __str__(self):
        return self.name

    @property
    def last_message(self):
        if self.chat_messages.count() == 0:
            return None
        return self.chat_messages.first()


class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.author.username, self.body)

    class Meta:
        ordering = ['-created']

app/chat/forms.py
from django import forms
from django.core.validators import FileExtensionValidator

from .models import PFP
from .validators import validate_image_file_size


class RegistrationForm(forms.Form):
    username = forms.CharField(label='username', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}), max_length=64)


class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=32, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}), max_length=64)


class PFPForm(forms.ModelForm):
    image = forms.ImageField(
        validators=[validate_image_file_size, FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])],
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = PFP
        fields = ['image']

app/chat/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import Form
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import View, TemplateView, ListView

from typing import Dict, Any

from .forms import RegistrationForm, LoginForm, PFPForm
from .models import User, PFP, ChatGroup


def lazy_background_video(request):
    """
    sends back partial with a video for background. Used within base.html file.
    """
    return render(request, "chat/partials/lazy_bg_video_partial.html")


"""
Authentication view classes and methods
"""


# also used by RegistrationView
def login_user_if_exists(request, form: Form) -> bool:
    user = authenticate(
        username=form.cleaned_data['username'],
        password=form.cleaned_data['password'],
    )
    if user:
        login(request, user)
        messages.success(request, 'Login succeeded!')
        return True
    return False

def redirect_to_me(request):
    """
    Redirects to the current user profile page
    """
    if request.user.is_authenticated:
        return redirect('chat:user_profile_self')
    else:
        messages.error(request, 'You have to be authenticated!')
        return redirect('chat:login')

class LoginView(View):
    # Login view class
    template_name = 'chat/login.html'

    def get(self, request):
        return render(request, self.template_name, context={'form': LoginForm})

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            if login_user_if_exists(request, form):
                redirect_to = request.POST.get('next')
                if redirect_to:
                    return redirect(redirect_to)

                return redirect('chat:user_profile_self')

        messages.error(request, 'Login failed!')
        return render(request, self.template_name, context={'form': form})


def user_logout(request):
    logout(request)

    messages.success(request, 'You have successfully logged out!')
    return redirect('chat:login')


class RegistrationView(View):
    # Registration view class
    template_name = 'chat/register.html'

    def get(self, request):
        return render(request, self.template_name, context={'form': RegistrationForm})

    def post(self, request):
        form = RegistrationForm(request.POST)

        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'],
            )

            messages.success(request, 'Registration success!')

            if login_user_if_exists(request, form):
                return redirect('chat:home')

        messages.error(request, 'Registration failed!')
        return render(request, self.template_name, context={'form': form})


"""
Home view class and methods
"""


@login_required(login_url=reverse_lazy('chat:login'))
@require_http_methods(["POST"])
def change_pfp(request):
    """
    Method to change profile picture. Image should be less than 1mb and has JPG, JPEG, PNG.
    """
    pfp = get_object_or_404(PFP, user=request.user)

    form = PFPForm(request.POST, request.FILES, instance=pfp)
    if form.is_valid():
        form.save()
        messages.success(request, 'Profile picture has been set successfully!')
    else:
        """sends back any validation errors that occurred"""
        for error_msg in form.errors.as_data()['image'][0]:
            full_message = "{}".format(error_msg)
            messages.error(request, full_message)
    return redirect('chat:home')


'''Home view class. User can see and change his profile data on this page'''


class HomeView(TemplateView):
    template_name = 'chat/home.html'
    extra_context = {
        'pfp_form': PFPForm,
    }


'''User profile view class'''


class UserProfileView(View):
    template_name = 'chat/profile.html'

    def get(self, request, *args, **kwargs):
        context: Dict[str, Any] = {
            'requested_user': None,
            'pfp_form': None
        }

        requested_user = None
        if 'pk' in kwargs:
            requested_user = User.objects.get(pk=kwargs['pk'])
        elif 'username' in kwargs:
            requested_user = User.objects.get(username=kwargs['username'])
        elif request.user.is_authenticated:
            requested_user = User.objects.get(pk=request.user.pk)

        if requested_user is None:
            messages.error(request, 'You have to be authenticated or enter a valid username or id of the user')
            return redirect('chat:login')

        # if the user is authenticated and is the same as the requested user he can change his profile picture
        if requested_user == request.user:
            context['pfp_form'] = PFPForm()

        context['requested_user'] = requested_user
        return render(request, self.template_name, context=context)


'''
Chat group view class and methods
'''


def lazy_messages(request, group_id: int):
    chat_group = get_object_or_404(ChatGroup, id=group_id)
    chat_messages = reversed(chat_group.chat_messages.all()[:30])

    return render(request, 'group_messages.html', {'chat_messages': chat_messages})

class ChatGroupListView(ListView):
    model = ChatGroup
    template_name = 'chat/chat_group_list.html'
    context_object_name = 'chat_groups'

    def get_queryset(self):
        return ChatGroup.objects.all()[:30]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['chat_groups'] = self.get_queryset()
        return context

class ChatGroupView(LoginRequiredMixin, View):
    template_name = 'chat/chat_group.html'

    login_url = reverse_lazy('chat:login')

    """
    The view can be accessed by either primary key or name of the group
    """

    def get(self, request, *args, **kwargs) -> HttpResponse:
        if 'pk' in kwargs:
            chat_group = get_object_or_404(ChatGroup, pk=kwargs['pk'])
        elif 'group_name' in kwargs:
            chat_group = get_object_or_404(ChatGroup, name=kwargs['group_name'])
        else:
            return HttpResponse('Group not found', status=404)

        chat_messages = reversed(chat_group.chat_messages.all()[:30])

        return render(request, self.template_name, {'group': chat_group, 'chat_messages': chat_messages})

    def handle_no_permission(self):
        messages.warning(self.request, "You need to log in to access this page.")
        return redirect(f"{self.login_url}?next={self.request.get_full_path()}")

app/chat/templates/chat/base.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'chat/bootstrap-5.3.3-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'chat/bootstrap-icons-1.11.3/bootstrap-icons-1.11.3/font/bootstrap-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'chat/css/base.css' %}">
    {% block meta %}
    {% endblock %}
</head>
<body class="overflow-x-hidden">
<div
        hx-get="{% url 'chat:lazy_bg_video' %}"
        hx-trigger="load"
        hx-swap="outerHTML"
        class="video-placeholder">
    <video autoplay muted loop class="background-video">
        <source src="{% static 'chat/vid/background-video-cheap.mp4' %}" type="video/mp4">
    </video>
</div>
<nav class="navbar mb-5">
    <div class="container d-flex flex-row justify-content-between ">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link" href="{% url 'chat:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'chat:chat_group_list' %}">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tools:svg_pixelation' %}">SVG Pixelation</a></li>
            </ul>
        </header>
        {% if user.is_authenticated %}
            <a href="{% url 'chat:logout' %}" class="btn btn-outline-danger p-2 d-flex flex-row gap-1">
                <i class="bi bi-box-arrow-right"></i>
                Logout
            </a>
        {% endif %}
    </div>
</nav>
<main class="main">
    <div class="outer-content-wrapper container py-5 border rounded-4">
        {% block content %}
        {% endblock %}
    </div>
    <div class="messages position-absolute bottom-0 end-0 mx-5">
        {% if messages %}
            <ul class="messages mt-5">
                {% for message in messages %}
                    <li class="message mt-3">
                        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                             role="alert">
                            <strong>{{ message.tags|title }}</strong> {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</main>
<script src="{% static 'chat/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'chat/htmx-2.0.4-dist/htmx.min.js' %}"></script>
<script>
    const current_path = window.location.pathname
    const nav_links = document.querySelectorAll(".nav-link")


    nav_links.forEach(link => {
        if (link.getAttribute("href") === current_path) {
            link.classList.add("active")
        }
    })
</script>
</body>
</html>

app/chat/templates/chat/chat_group.html
{% extends 'chat/base.html' %}
{% load custom_filters %}
{% load static %}

{% block meta %}
    <title>{{ group.name|title }} Chat</title>
    <link rel="stylesheet" href="{% static 'chat/css/group_chat.css' %}">
{% endblock %}

{% block content %}
    <div style="height: 75vh"
         class="chat container border rounded-4 overflow-hidden px-0 d-flex flex-column-reverse w-75 mx-auto">
        <form autocomplete="off" id="chat-form" class="row m-0 p-0 border-top">
            <input type="text" name="message" class="col border-0"/>
            <button type="submit" name="submit" value="Send" class="btn btn-primary col-1 border-0 rounded-0 hover">
                <i class="bi bi-send-fill"></i>
            </button>
        </form>
        <div class="message-box flex-row-reverse overflow-y-scroll row m-0 px-0 pt-5 pb-3">
            {% for message in chat_messages %}
                {% if message.author.username == user.username %}
                    <div class="message row justify-content-start" id="message_{{ message.pk }}">
                        <div class="row flex-row-reverse">
                            <div class="msg-wrapper-self border rounded p-2 pb-0 m-1 col-auto">
                                <img style="aspect-ratio: 1/1; width: 32px" src="{{ message.author.pfp.image.url }}"
                                     alt="Profile Picture"
                                     class="rounded-circle">
                                <span class="fw-bold">
                                    From: <a class="link-dark" href="{% url 'chat:user_profile' message.author.pk %}">
                                    You
                                </a></span>
                                <br>
                                <p class="border-top m-0">{{ message.body }}</p>
                                <span class="date-created fs-6">{{ message.created|formatiso }}</span>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="message row justify-content-start" id="message_{{ message.pk }}">
                        <div class="row">
                            <div class="msg-wrapper border rounded p-2 pb-0 m-1 col-auto">
                                <img style="aspect-ratio: 1/1; width: 32px" src="{{ message.author.pfp.image.url }}"
                                     alt="Profile Picture"
                                     class="rounded-circle">
                                <span class="fw-bold">
                                    From: <a class="link-dark" href="{% url 'chat:user_profile' message.author.pk %}">
                                    {{ message.author }}
                                    </a></span>
                                <br>
                                <p class="border-top m-0">{{ message.body }}</p>
                                <span class="date-created fs-6">{{ message.created.isoformat }}</span>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="header border-bottom px-3 py-2 w-100">
            <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
                 class="position-absolute">
                <circle cx="12" cy="12" r="4" fill="limegreen">
                    <animate attributeName="opacity" values="0.6;1;0.6" dur="1.5s" repeatCount="indefinite"/>
                </circle>
                <circle cx="12" cy="12" r="5" fill="limegreen" opacity="0.5">
                    <animate attributeName="r" values="5;7;5" dur="1.5s" repeatCount="indefinite"/>
                    <animate attributeName="opacity" values="0.5;0.2;0.5" dur="1.5s" repeatCount="indefinite"/>
                </circle>
            </svg>
            <span class="online-counter d-flex flex-row-reverse align-content-center justify-content-center">
            <span id="counter">0</span>
        </span>
        </div>
    </div>
    <script type="text/javascript">

        // Handshake and connection to the websocket server.

        let protocol = window.location.protocol === "https:" ? "wss" : "ws"
        let url = `${protocol}://${window.location.host}/ws/chat/groups/{{ group.pk }}/`

        const chatSocket = new WebSocket(url)

        /*
        *
        *   Functions for building messages and its appearance
        *
        * */

        //  Format ISO 8601 to the users local time string
        function formatDate(raw_date) {
            let date = new Date(raw_date);
            return date.toLocaleString();
        }

        // Format the date for all the messages loaded
        document.addEventListener('DOMContentLoaded', function () {
            const messages = document.querySelectorAll('.message')
            messages.forEach(message => {
                let date = message.querySelector('.date-created')
                let raw_date = date.innerText
                date.innerText = formatDate(raw_date)
            })
        })

        function build_user_message(data) {
            /*  building notifications from the users  */

            // your messages
            if (data.author === '{{ user.username }}') {
                return `<div class="row justify-content-start">
                            <div class="row flex-row-reverse">
                                <div class="msg-wrapper-self border rounded p-2 m-1 col-auto">
                                    <img style="aspect-ratio: 1/1; width: 32px" src="${data.pfp}" alt="Profile Picture" class="rounded-circle">
                                    <span class="fw-bold">From: You</span>
                                    <br>
                                    <p class="border-top m-0">${data.message}</p>
                                    <span class="date-created fs-6">${formatDate(data.date_created)}</span>
                                </div>
                            </div>
                        </div>`
            }

            // other user  messages
            return `<div class="row justify-content-start">
                        <div class="row">
                            <div class="msg-wrapper border rounded p-2 m-1 col-auto">
                                <img style="aspect-ratio: 1/1; width: 32px" src="${data.pfp}" alt="Profile Picture" class="rounded-circle">
                                <span class="fw-bold">From: ${data.author}</span>
                                <br>
                                <p class="border-top m-0">${data.message}</p>
                                <span class="date-created fs-6">${formatDate(data.date_created)}</span>
                            </div>
                        </div>
                    </div>`
        }

        function build_notification_message(data) {
            /*  building notifications from the server  */

            //  get rid of previous notifications
            let previous_notification = document.getElementById('chat-notification')
            if (previous_notification !== null) {
                previous_notification.remove()
            }

            return `<div id="chat-notification" class="msg-notification-${data.style} row justify-content-center w-75 border-top my-3 mx-auto pt-2">
                        <p align="center" class="text-${data.style}-emphasis">${data.message}</p>
                    </div>`
        }

        /*
        *
        *   Receiving and sending data
        *
        * */

        //  Receive and process data from the server
        chatSocket.onmessage = function (e) {
            let data = JSON.parse(e.data)
            console.log(data)

            let chat_box = document.querySelector('.message-box')
            let msg_element = null
            if (data.type === 'chat') {
                msg_element = build_user_message(data)
            }
            if (data.type === 'notification') {
                msg_element = build_notification_message(data)

                if (data['user_count'] !== undefined) {
                    let counter = document.getElementById('counter')
                    counter.innerText = data['user_count'].toString() + ' online'
                }
            }

            chat_box.insertAdjacentHTML('beforeend', msg_element)
            chat_box.scrollTo(0, chat_box.scrollHeight)
        }

        //  Send message to the server
        let chat_form = document.getElementById('chat-form')
        chat_form.addEventListener('submit', (e) => {
            e.preventDefault()
            let message = e.target.message.value
            if (message !== '') {
                chatSocket.send(JSON.stringify({
                    'author': '{{ user.pk }}',
                    'group': '{{ group.pk }}',
                    'message': message
                }))
            }
            chat_form.reset()
        })
    </script>
{% endblock %}

app/chat/templates/chat/chat_group_list.html
{% extends 'chat/base.html' %}
{% load static %}

{% block meta %}
    <title>Groups</title>
    <link rel="stylesheet" href="{% static 'chat/css/chat_group_list.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h3 class="mb-5">Available groups</h3>
        <ul class="container-fluid">
            {% for group in chat_groups %}
                <li class="group row justify-content-between border border-light border-1 rounded-3 py-3 my-3">
                    <h3 class="group-name col-3 d-flex align-content-center my-auto justify-content-center">{{ group.name }}</h3>
                    <div class="last_message col d-flex flex-row gap-2">
                        <span class="text-body-secondary">Recent</span>
                        <div class="message align-self-start d-flex flex-column p-2 gap-2 bg-white border border-1 rounded-2"
                             style="min-width: 10vw">
                            {% if group.last_message %}
                                <div id="author_{{ group.last_message.author.pk }}"
                                     class="author d-flex flex-row gap-2 border-bottom border-1 pb-2">
                                    <img src="{{ group.last_message.author.pfp.image.url }}" alt="Avatar"
                                         class="pfp rounded-circle" width="24" height="24">

                                    <a href="{% url 'chat:user_profile' group.last_message.author.pk %}"
                                       class="link-dark">
                                        {% if group.last_message.author.username == user.username %}
                                            <strong>You</strong>
                                        {% else %}
                                            <strong>{{ group.last_message.author.username }}</strong>
                                        {% endif %}
                                    </a>
                                </div>
                                <span class="message-body">{{ group.last_message.body }}</span>
                            {% else %}
                                <span>No recent activity</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="join_chat col d-flex flex-row justify-content-end">
                        <a class="btn btn-primary px-4 py-2 my-auto"
                           href="{% url 'chat:chat_group' group.id %}">Join</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <script>
        const last_message_body = document.querySelector('.message-body');

        if (last_message_body) {
            const message = last_message_body.innerText;
            let maxLength = 40;
            if (message.length > maxLength) {
                last_message_body.innerText = message.substring(0, maxLength) + '...';
            }
        }
    </script>
{% endblock %}

app/chat/templates/chat/home.html
{% extends 'chat/base.html' %}
{% load static %}

{% block meta %}
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'chat/css/home.css' %}">
{% endblock %}

{% block content %}
    <div class="h-100">
        <div class="w-75 mx-auto">
            {% if user.is_authenticated %}
                <h3>
                    Hello {{ user.username }}!
                    {% if user.is_staff %}
                        <small class="text-body-secondary">administrator</small>
                    {% endif %}
                </h3>
                <img class="rounded-circle my-3" style="aspect-ratio: 1/1; width: 128px" src="{{ user.pfp.image.url }}"
                     alt="Profile Picture">
                <form action="{% url 'chat:upload_pfp' %}" method="post" enctype="multipart/form-data"
                      class="pfp-form rounded-2 pt-3 mt-2 w-50">
                    {% csrf_token %}
                    <h6><label for="{{ form.image.id_for_label }}"
                           class="form-label">Upload profile picture </label></h6>
                    <div class="input-group">
                        {{ pfp_form.image }}
                        <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Submit
                        </button>
                    </div>
                </form>
                <hr>
                <div class="d-flex flex-column w-50">
                    <div class="input-group mb-3">
                        <span class="input-group-text">Email</span>
                        <input type="text" class="form-control" placeholder="{{ user.email }}" aria-label="Email"
                               readonly>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">First name</span>
                        <input type="text" class="form-control" placeholder="{{ user.first_name }}"
                               aria-label="First name"
                               readonly>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">Last name</span>
                        <input type="text" class="form-control" placeholder="{{ user.last_name }}"
                               aria-label="Last name"
                               readonly>
                    </div>
                </div>
            {% else %}
                <h1>Hello guest! Please log in if you want to access any chat!</h1>
                <a href="{% url 'chat:login' %}"
                   class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Login
                    --></a>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/chat/templates/chat/login.html
{% extends 'chat/base.html' %}
{% load static %}

{% block meta %}
    <title>Login</title>
{% endblock %}

{% block content %}
    <div class="w-50 mx-auto">
        <h1>Login</h1>
        <form action="{% url 'chat:login' %}" method="post" class="mb-3">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            <div class="mb-2 form-floating">
                {{ form.username }}
                <label for="{{ form.username.id_for_label }}"
                       class="form-label text-capitalize">{{ form.username.label }}</label>
            </div>
            <div class="mb-2 form-floating">
                {{ form.password }}
                <label for="{{ form.password.id_for_label }}"
                       class="form-label text-capitalize">{{ form.password.label }}</label>
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
        <a href="{% url 'chat:signup' %}"
           class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Sing Up
            --></a>
    </div>
{% endblock %}